name: Release

on:
  push:
    branches:
      - main
      - next

jobs:
  Validate:
    uses: ./.github/workflows/validate.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write

  Release:
    needs: Validate
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Release
        uses: agilecustoms/release@main
        with:
          floating-tags: false
          npm-extra-deps: conventional-changelog-conventionalcommits@9.1.0
        env:
          GH_TOKEN: ${{ secrets.GH_PUBLIC_RELEASES_TOKEN }}
