name: Validate

on:
  push:
    branches-ignore:
      - main
#      - next
  workflow_call:

jobs:
  Validate:
    name: Validate-infra
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform validate
